import { describe, it, expect } from 'vitest';
import { generateMigrationDoc } from '../../../src/strategies/migration-doc.js';
import type { AnalyzeResult, ExtendedAnalysis } from '../../../src/types/index.js';

function makeAnalysis(overrides: Partial<AnalyzeResult> = {}): AnalyzeResult {
  return {
    packages: [
      { name: 'pkg-a', version: '1.0.0', path: '/tmp/a', dependencies: {}, devDependencies: {}, scripts: {} },
      { name: 'pkg-b', version: '2.0.0', path: '/tmp/b', dependencies: {}, devDependencies: {}, scripts: {} },
    ],
    conflicts: [],
    collisions: [],
    crossDependencies: [],
    complexityScore: 25,
    recommendations: [],
    ...overrides,
  };
}

function makeExtended(overrides: Partial<ExtendedAnalysis> = {}): ExtendedAnalysis {
  return {
    environment: [],
    packageManager: [],
    tooling: [],
    ci: [],
    publishing: [],
    repoRisks: [],
    riskSummary: {
      classification: 'straightforward',
      reasons: [],
      topFindings: [],
    },
    ...overrides,
  };
}

describe('generateMigrationDoc', () => {
  it('should generate a markdown document with header', () => {
    const doc = generateMigrationDoc(makeAnalysis());
    expect(doc).toContain('# Migration Guide');
    expect(doc).toContain('Generated by Monotize');
  });

  it('should include complexity section', () => {
    const doc = generateMigrationDoc(makeAnalysis({ complexityScore: 42 }));
    expect(doc).toContain('## Complexity');
    expect(doc).toContain('**Score:** 42/100');
    expect(doc).toContain('**Packages:** 2');
  });

  it('should include conflict count', () => {
    const doc = generateMigrationDoc(makeAnalysis({
      conflicts: [
        { name: 'lodash', versions: [{ version: '4.17.21', source: 'a', type: 'dependencies' }], severity: 'minor' },
      ],
    }));
    expect(doc).toContain('**Conflicts:** 1');
  });

  it('should include collision count', () => {
    const doc = generateMigrationDoc(makeAnalysis({
      collisions: [{ path: '.gitignore', sources: ['a', 'b'], suggestedStrategy: 'merge' }],
    }));
    expect(doc).toContain('**File Collisions:** 1');
  });

  it('should include circular dependencies when present', () => {
    const doc = generateMigrationDoc(makeAnalysis({
      circularDependencies: [{ packages: ['a', 'b'], cycle: ['a', 'b', 'a'] }],
    }));
    expect(doc).toContain('**Circular Dependencies:** 1');
  });

  it('should include suggested order of operations', () => {
    const doc = generateMigrationDoc(makeAnalysis());
    expect(doc).toContain('## Suggested Order of Operations');
    expect(doc).toContain('**Prepare**');
    expect(doc).toContain('**Verify**');
    expect(doc).toContain('**Archive**');
  });

  it('should include recommendations when present', () => {
    const doc = generateMigrationDoc(makeAnalysis({
      recommendations: ['Use pnpm for workspace management', 'Add shared tsconfig'],
    }));
    expect(doc).toContain('## Recommendations');
    expect(doc).toContain('Use pnpm for workspace management');
    expect(doc).toContain('Add shared tsconfig');
  });

  it('should not include recommendations section when empty', () => {
    const doc = generateMigrationDoc(makeAnalysis({ recommendations: [] }));
    expect(doc).not.toContain('## Recommendations');
  });

  describe('with extended analysis', () => {
    it('should include risk assessment for straightforward classification', () => {
      const doc = generateMigrationDoc(makeAnalysis(), makeExtended({
        riskSummary: {
          classification: 'straightforward',
          reasons: [],
          topFindings: [],
        },
      }));
      expect(doc).toContain('## Risk Assessment');
      expect(doc).toContain('Straightforward');
    });

    it('should include risk assessment for needs-decisions classification', () => {
      const doc = generateMigrationDoc(makeAnalysis(), makeExtended({
        riskSummary: {
          classification: 'needs-decisions',
          reasons: ['Multiple CI systems detected'],
          topFindings: [],
        },
      }));
      expect(doc).toContain('Needs Decisions');
      expect(doc).toContain('Multiple CI systems detected');
    });

    it('should include risk assessment for complex classification', () => {
      const doc = generateMigrationDoc(makeAnalysis(), makeExtended({
        riskSummary: {
          classification: 'complex',
          reasons: ['Submodules detected', 'LFS in use'],
          topFindings: [],
        },
      }));
      expect(doc).toContain('Complex');
      expect(doc).toContain('Submodules detected');
      expect(doc).toContain('LFS in use');
    });

    it('should include top risks with findings', () => {
      const doc = generateMigrationDoc(makeAnalysis(), makeExtended({
        riskSummary: {
          classification: 'complex',
          reasons: [],
          topFindings: [
            {
              id: 'risk-submodules',
              title: 'Git submodules detected',
              severity: 'error',
              confidence: 'high',
              evidence: [{ path: '.gitmodules', snippet: 'submodule "lib"' }],
              suggestedAction: 'Convert submodules to regular packages',
            },
          ],
        },
      }));
      expect(doc).toContain('## Top Risks');
      expect(doc).toContain('### Git submodules detected');
      expect(doc).toContain('**Severity:** error');
      expect(doc).toContain('Convert submodules to regular packages');
      expect(doc).toContain('.gitmodules');
    });

    it('should include top risks with evidence without snippet', () => {
      const doc = generateMigrationDoc(makeAnalysis(), makeExtended({
        riskSummary: {
          classification: 'complex',
          reasons: [],
          topFindings: [
            {
              id: 'risk-large',
              title: 'Large files detected',
              severity: 'warn',
              confidence: 'high',
              evidence: [{ path: 'data/big-file.bin' }],
              suggestedAction: 'Move to LFS',
            },
          ],
        },
      }));
      expect(doc).toContain('data/big-file.bin');
    });

    it('should include extended analysis sections with findings', () => {
      const doc = generateMigrationDoc(makeAnalysis(), makeExtended({
        environment: [
          {
            id: 'env-node-mismatch',
            title: 'Node.js version mismatch',
            severity: 'warn',
            confidence: 'high',
            evidence: [{ path: '.nvmrc' }],
            suggestedAction: 'Standardize on Node 20',
          },
        ],
        ci: [
          {
            id: 'ci-gh-actions',
            title: 'GitHub Actions detected',
            severity: 'info',
            confidence: 'high',
            evidence: [{ path: '.github/workflows/ci.yml' }],
            suggestedAction: 'Merge workflows',
          },
        ],
      }));
      expect(doc).toContain('## Environment');
      expect(doc).toContain('[!] Node.js version mismatch');
      expect(doc).toContain('Standardize on Node 20');
      expect(doc).toContain('## CI/CD');
      expect(doc).toContain('[i] GitHub Actions detected');
    });

    it('should skip extended sections with no findings', () => {
      const doc = generateMigrationDoc(makeAnalysis(), makeExtended({
        environment: [],
        tooling: [],
      }));
      expect(doc).not.toContain('## Environment');
      expect(doc).not.toContain('## Tooling');
    });

    it('should use !! icon for critical/error severity', () => {
      const doc = generateMigrationDoc(makeAnalysis(), makeExtended({
        repoRisks: [
          {
            id: 'risk-critical',
            title: 'Critical risk',
            severity: 'critical',
            confidence: 'high',
            evidence: [],
            suggestedAction: 'Fix immediately',
          },
        ],
      }));
      expect(doc).toContain('[!!] Critical risk');
    });
  });

  describe('with findings and decisions', () => {
    it('should include required decisions', () => {
      const doc = generateMigrationDoc(makeAnalysis({
        findings: {
          decisions: [
            {
              kind: 'package-manager',
              description: 'Choose package manager',
              suggestedAction: 'Use pnpm',
            },
            {
              kind: 'conflict-strategy',
              description: 'Resolve lodash version conflict',
            },
          ],
          conflictInsights: [],
          collisionInsights: [],
        },
      }));
      expect(doc).toContain('## Required Decisions');
      expect(doc).toContain('**package-manager**: Choose package manager');
      expect(doc).toContain('Suggested: Use pnpm');
      expect(doc).toContain('**conflict-strategy**: Resolve lodash version conflict');
    });
  });
});
