import type { ExtendedAnalysis, AnalyzeResult, RiskSummary } from '../types/index.js';

/**
 * Generate a MIGRATION.md document from analysis results.
 */
export function generateMigrationDoc(
  analysis: AnalyzeResult,
  extended?: ExtendedAnalysis,
): string {
  const lines: string[] = [];

  lines.push('# Migration Guide');
  lines.push('');
  lines.push(`> Generated by Monotize on ${new Date().toISOString()}`);
  lines.push('');

  // Risk Summary
  if (extended?.riskSummary) {
    lines.push('## Risk Assessment');
    lines.push('');
    lines.push(`**Classification:** ${formatClassification(extended.riskSummary)}`);
    lines.push('');
    if (extended.riskSummary.reasons.length > 0) {
      lines.push('**Reasons:**');
      for (const reason of extended.riskSummary.reasons) {
        lines.push(`- ${reason}`);
      }
      lines.push('');
    }
  }

  // Top Risks
  if (extended?.riskSummary?.topFindings?.length) {
    lines.push('## Top Risks');
    lines.push('');
    for (const finding of extended.riskSummary.topFindings) {
      lines.push(`### ${finding.title}`);
      lines.push('');
      lines.push(`- **Severity:** ${finding.severity}`);
      lines.push(`- **Action:** ${finding.suggestedAction}`);
      if (finding.evidence.length > 0) {
        lines.push(`- **Evidence:**`);
        for (const e of finding.evidence.slice(0, 3)) {
          lines.push(`  - ${e.path}${e.snippet ? `: ${e.snippet}` : ''}`);
        }
      }
      lines.push('');
    }
  }

  // Complexity
  lines.push('## Complexity');
  lines.push('');
  lines.push(`- **Score:** ${analysis.complexityScore}/100`);
  lines.push(`- **Packages:** ${analysis.packages.length}`);
  lines.push(`- **Conflicts:** ${analysis.conflicts.length}`);
  lines.push(`- **File Collisions:** ${analysis.collisions.length}`);
  if (analysis.circularDependencies?.length) {
    lines.push(`- **Circular Dependencies:** ${analysis.circularDependencies.length}`);
  }
  lines.push('');

  // Required Decisions
  if (analysis.findings?.decisions?.length) {
    lines.push('## Required Decisions');
    lines.push('');
    for (const decision of analysis.findings.decisions) {
      lines.push(`- [ ] **${decision.kind}**: ${decision.description}`);
      if (decision.suggestedAction) {
        lines.push(`  - Suggested: ${decision.suggestedAction}`);
      }
    }
    lines.push('');
  }

  // Suggested Order of Operations
  lines.push('## Suggested Order of Operations');
  lines.push('');
  lines.push('1. **Prepare** - Standardize Node.js versions, package managers, and build scripts');
  lines.push('2. **Plan** - Generate and review the migration plan');
  lines.push('3. **Merge** - Execute the migration');
  lines.push('4. **Configure** - Set up shared tooling (TypeScript, ESLint, Prettier)');
  lines.push('5. **Verify** - Run verification checks');
  lines.push('6. **Archive** - Deprecate source repositories');
  lines.push('');

  // Extended sections
  if (extended) {
    const sections: Array<{ title: string; findings: typeof extended.environment }> = [
      { title: 'Environment', findings: extended.environment },
      { title: 'Package Manager', findings: extended.packageManager },
      { title: 'Tooling', findings: extended.tooling },
      { title: 'CI/CD', findings: extended.ci },
      { title: 'Publishing', findings: extended.publishing },
      { title: 'Repository Risks', findings: extended.repoRisks },
    ];

    for (const section of sections) {
      if (section.findings.length === 0) continue;
      lines.push(`## ${section.title}`);
      lines.push('');
      for (const f of section.findings) {
        const icon = f.severity === 'critical' || f.severity === 'error' ? '!!' :
                     f.severity === 'warn' ? '!' : 'i';
        lines.push(`- [${icon}] ${f.title}`);
        lines.push(`  - ${f.suggestedAction}`);
      }
      lines.push('');
    }
  }

  // Recommendations
  if (analysis.recommendations.length > 0) {
    lines.push('## Recommendations');
    lines.push('');
    for (const rec of analysis.recommendations) {
      lines.push(`- ${rec}`);
    }
    lines.push('');
  }

  return lines.join('\n');
}

function formatClassification(summary: RiskSummary): string {
  switch (summary.classification) {
    case 'straightforward':
      return 'Straightforward - Migration should be smooth';
    case 'needs-decisions':
      return 'Needs Decisions - Some items require human judgment';
    case 'complex':
      return 'Complex - Significant manual work required';
  }
}
