import type { PlanFile } from '../types/index.js';

export interface WorkflowGeneratorOptions {
  /** Package manager command (e.g. 'pnpm', 'yarn', 'npm') */
  packageManager?: string;
  /** Default verify tier for CI */
  verifyTier?: 'static' | 'install' | 'full';
  /** Node.js version for CI */
  nodeVersion?: string;
}

/**
 * Generate a path-filtered GitHub Actions workflow for a monorepo.
 * Each package gets its own path filter so only affected packages are tested.
 */
export function generatePathFilteredWorkflow(
  packageNames: string[],
  packagesDir: string,
  options: WorkflowGeneratorOptions = {},
): PlanFile {
  const pm = options.packageManager || 'pnpm';
  const nodeVersion = options.nodeVersion || '20';
  const installCmd = pm === 'npm' ? 'npm ci' : pm === 'yarn' ? 'yarn install --frozen-lockfile' : 'pnpm install --frozen-lockfile';
  const pmSetup = pm === 'pnpm' ? `
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9` : '';

  // Build path filters for each package
  const pathFilters = packageNames
    .map((pkg) => `        ${pkg}:\n          - '${packagesDir}/${pkg}/**'`)
    .join('\n');

  // Build matrix entries
  const matrixIncludes = packageNames
    .map((pkg) => `          - package: ${pkg}`)
    .join('\n');

  const content = `# Generated by Monotize - path-filtered CI workflow
name: CI

on:
  push:
    branches: [main, master]
    paths:
${packageNames.map((pkg) => `      - '${packagesDir}/${pkg}/**'`).join('\n')}
      - 'package.json'
      - 'pnpm-lock.yaml'
      - '.github/workflows/monotize-ci.yml'
  pull_request:
    branches: [main, master]
    paths:
${packageNames.map((pkg) => `      - '${packagesDir}/${pkg}/**'`).join('\n')}
      - 'package.json'
      - 'pnpm-lock.yaml'
      - '.github/workflows/monotize-ci.yml'

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
${packageNames.map((pkg) => `      ${pkg}: \${{ steps.filter.outputs.${pkg} }}`).join('\n')}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
${pathFilters}

  build-test:
    needs: detect-changes
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
${matrixIncludes}
    if: >-
${packageNames.map((pkg) => `      needs.detect-changes.outputs.${pkg} == 'true'`).join(' ||\n')}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '${nodeVersion}'${pmSetup}

      - name: Install dependencies
        run: ${installCmd}

      - name: Build
        run: ${pm} run build --filter=\${{ matrix.package }} 2>/dev/null || true
        working-directory: .

      - name: Test
        run: ${pm} run test --filter=\${{ matrix.package }} 2>/dev/null || true
        working-directory: .
`;

  return {
    relativePath: '.github/workflows/monotize-ci.yml',
    content,
  };
}

/**
 * Move existing workflows to a legacy directory.
 * Returns the list of files that would be moved (for plan serialization).
 */
export function planLegacyWorkflowMoves(
  existingWorkflows: string[],
): Array<{ from: string; to: string }> {
  return existingWorkflows.map((wf) => ({
    from: `.github/workflows/${wf}`,
    to: `.github/workflows/legacy/${wf}`,
  }));
}
